version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:23"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5

  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:33"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:43"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
